name: Propose a talk / workshop
description: "Propose a talk or workshop for upcoming meetup/event"
labels:
- talk-proposal
assignees: []
body:
- type: markdown
  attributes:
    value: |
      👋 Thank you for showing interest in submitting a talk. You can
      submit any talks which are in or related to Python
      Programming language but also any programming language, new
      libraries learned, some awesome projects you worked on,
      something new in Data Science, Machine Learning, Automation,
      Cloud, Containers, Hardware.

- type: input
  id: title
  attributes:
    label: Title of the talk
    description: "Please include a short title"
  validations:
    required: true

- type: textarea
  id: description
  attributes:
    label: Description
    description: "Please include brief abstract about your talk"
  validations:
    required: true

- type: dropdown
  id: format
  attributes:
    label: What format do you have in mind for your talk?
    options:
      - Talk
      - Workshop
  validations:
    required: true

- type: textarea
  id: toc
  attributes:
    label: Table of contents
    description: "Please add an outline of your talk"
    placeholder: |
      A few bullet points which you will be covering during the talk
      can be added here. You can update this later as well.
  validations:
    required: true

- type: dropdown
  id: domain
  attributes:
    label: What domain would you say your talk falls under?
    options:
      - Core Python
      - Data Science & Machine Learning
      - Web Dev
      - CLI & Tooling
      - Testing
      - Embedded
      - Research
      - AI
      - Web3
      - BotDev
  validations:
    required: true

- type: input
  id: duration
  attributes:
    label: "Duration in minutes (including Q&A)"
    description: "Please add estimated duration of the talk including Q&A"
  validations:
    required: true

- type: textarea
  id: prerequisites
  attributes:
    label: Prerequisites
    description: "Any specific requirement from audience for the talk?"
    placeholder: |
      If you have any prerequisites like software, tools set up on
      machine etc, please include it here.

- type: input
  id: speaker-social-x
  attributes:
    label: "Speaker X(Twitter) Account link (Optional)"
    description: "Please add your twitter account link here, if you wish us to tag you."
  validations:
    required: false

- type: input
  id: speaker-pic
  attributes:
    label: "Profile Picture"
    description: "We will use this picture while creating a poster for the event. You can use animated or any annonymous image if you do not wish to display your picture publicly."
  validations:
    required: false

- type: textarea
  id: bio
  attributes:
    label: Speaker bio
    description: "Please add your introduction"
    placeholder: |
      Also add link to your Twitter (make sure you follow __bangpypers__
      so that we can DM you there) or LinkedIn so that we can
      coordinate with you before the event. If you don't want to share
      any of the above, please send a direct message to any of the 
      volunteers on discord with subject: "Contact details for the talk".
  validations:
    required: true

- type: checkboxes
  id: req
  attributes:
    label: The talk/workshop speaker agrees to
    description: "You can keep the fields unchecked on which you don't agree."
    options:
    - label: "Share the slides, code snippets and other material used during the talk"
      required: true
    - label: |
        If the talk is recorded, you grant the permission to release
        the video on [BangPyper's YouTube
        channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
        under [CC-BY-4.0
        license](https://creativecommons.org/licenses/by/4.0/)
    - label: |
        Not do any hiring pitches during the talk and follow the [Code
        of
        Conduct](https://bangalore.pythonindia.org/coc/)
      required: true
- type: markdown
  attributes:
    value: |
       After submitting the issue, please fill this form to share your contact details with the organizers: https://forms.gle/cRx2RPnPbXKkmP2f9
